[book]
authors = ["ollb"]
language = "en"
multilingual = false
src = "src"
title = "build-term.nvim"

[output.html]
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/ollbx/build-term.nvim"
